runtime: php55

handlers:
  - url: /styles
    static_dir: styles

  - url: /images/(.*\.(https://storage.cloud.google.com/syifa-hacks.appspot.com/syifa.jpeg))
    static_files: images/\1
    upload: /images/(.*\.(https://storage.cloud.google.com/syifa-hacks.appspot.com/syifa.jpeg))

  - url: /.*
    script: index.php
